enum COMMON_MESSAGES {}

enum USER_MESSAGES {
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  LAST_NAME_TOO_SMALL = "LAST_NAME_TOO_SMALL",
  FIRST_NAME_TOO_SMALL = "FIRST_NAME_TOO_SMALL",
  INVALID_EMAIL = "INVALID_EMAIL",
  PASSWORD_TOO_SMALL = "PASSWORD_TOO_SMALL",
  PASSWORD_TOO_LARGE = "PASSWORD_TOO_LARGE",
  FIRST_NAME_TOO_LARGE = "FIRST_NAME_TOO_LARGE",
  LAST_NAME_TOO_LARGE = "LAST_NAME_TOO_LARGE",
  USER_CREATION_SUCCESS = "USER_CREATION_SUCCESS",
  USER_CREATION_FAILED = "USER_CREATION_FAILED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED = "USER_LOGIN_FAILED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS",
}

export { COMMON_MESSAGES, USER_MESSAGES };
