enum COMMON_MESSAGES {}

enum USER_MESSAGES {
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  LAST_NAME_TOO_SMALL = "LAST_NAME_TOO_SMALL",
  FIRST_NAME_TOO_SMALL = "FIRST_NAME_TOO_SMALL",
  INVALID_EMAIL = "INVALID_EMAIL",
  PASSWORD_TOO_SMALL = "PASSWORD_TOO_SMALL",
  PASSWORD_TOO_LARGE = "PASSWORD_TOO_LARGE",
  FIRST_NAME_TOO_LARGE = "FIRST_NAME_TOO_LARGE",
  LAST_NAME_TOO_LARGE = "LAST_NAME_TOO_LARGE",
  USER_CREATION_SUCCESS = "USER_CREATION_SUCCESS",
  USER_CREATION_FAILED = "USER_CREATION_FAILED",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILED = "USER_LOGIN_FAILED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS",
  USER_FETCHED_FAILED = "USER_FETCHED_FAILED",
  USER_ID_REQUIRED = "USER_ID_REQUIRED",
}

enum QUESTION_MESSAGES {
  QUESTION_REQUIRED = "QUESTION_REQUIRED",
  QUESTION_TOO_LONG = "QUESTION_TOO_LONG",
  QUESTION_TOO_SMALL = "QUESTION_TOO_SMALL",
  OPTION_REQUIRED = "OPTION_REQUIRED",
  OPTION_TOO_LONG = "OPTION_TOO_LONG",
  OPTION_TOO_SMALL = "OPTION_TOO_SMALL",
}

enum CONTEST_MESSAGES {
  CONTEST_NOT_FOUND = "CONTEST_NOT_FOUND",
  CONTEST_CREATION_SUCCESS = "CONTEST_CREATION_SUCCESS",
  CONTEST_CREATION_FAILED = "CONTEST_CREATION_FAILED",
  CONTEST_FETCH_SUCCESS = "CONTEST_FETCH_SUCCESS",
  CONTEST_FETCH_FAILED = "CONTEST_FETCH_FAILED",
  CONTEST_UPDATE_SUCCESS = "CONTEST_UPDATE_SUCCESS",
  CONTEST_UPDATE_FAILED = "CONTEST_UPDATE_FAILED",
  CONTEST_DELETE_SUCCESS = "CONTEST_DELETE_SUCCESS",
  CONTEST_DELETE_FAILED = "CONTEST_DELETE_FAILED",
  CONTEST_ID_REQUIRED = "CONTEST_ID_REQUIRED",

  CONTEST_NAME_TOO_SMALL = "CONTEST_NAME_TOO_SMALL",
  CONTEST_NAME_TOO_LARGE = "CONTEST_NAME_TOO_LARGE",
  CONTEST_DESCRIPTION_TOO_SMALL = "CONTEST_DESCRIPTION_TOO_SMALL",
  CONTEST_DESCRIPTION_TOO_LARGE = "CONTEST_DESCRIPTION_TOO_LARGE",
  CONTEST_START_DATE_INVALID = "CONTEST_START_DATE_INVALID",
  CONTEST_END_DATE_INVALID = "CONTEST_END_DATE_INVALID",
  CONTEST_STARTDATE_CAN_NOT_BE_AFTER_ENDDATE = "CONTEST_STARTDATE_CAN_NOT_BE_AFTER_ENDDATE",
  START_DATE_REQUIRED = "START_DATE_REQUIRED",
  END_DATE_REQUIRED = "END_DATE_REQUIRED",
  ROLE_REQUIRED = "ROLE_REQUIRED",
  INVALID_ROLE = "INVALID_ROLE",
}

export { COMMON_MESSAGES, USER_MESSAGES, CONTEST_MESSAGES, QUESTION_MESSAGES };
